server:
  http_listen_port: 9080
  grpc_listen_port: 9096

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push # Loki service name in docker-compose

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: dockerlogs
          __path__: /var/lib/docker/containers/*/*log

    # Discovers Docker containers and extracts labels for Loki
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        # Default labels from Docker will be added: container_id, container_name, image, etc.
    relabel_configs:
      # Add a service label based on the container name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: service